### PR TITLE
Catcher restriction on apply

### PR DESCRIPTION
**Pull request by IrrationalCucumber**
Catcher cannot apply if he/she has/have an ongoing errand
Employer will now be the one to set "Mark as Complete" to the errand instead of Catcher
Catcher will be able to apply again if Employer update the Errand transaction to Complete

### CODE REVIEW

**Review by markdannim — COMMENTED** [review]
Screenshot 2024-12-21 140203
Nitry ko buhat new account employer and catcher akong giverify both.  Si catcher di ka kitag apply button

**Comment by IrrationalCucumber** [comment]
> Screenshot 2024-12-21 140203 Nitry ko buhat new account employer and catcher akong giverify both. Si catcher di ka kitag apply button

check new db structure sa backend

**Review by markdannim — COMMENTED** [review]
Pwede like inig human apply sa catcher, bisag pending pa ang application request kay di pa siya pwede makaapply lain errands. Nitry ko apply lain errands while pending pa application request. Ang mahitabo kay makaapply siyag lain errands.

**Comment by IrrationalCucumber** [comment]
> Pwede like inig human apply sa catcher, bisag pending pa ang application request kay di pa siya pwede makaapply lain errands. Nitry ko apply lain errands while pending pa application request. Ang mahitabo kay makaapply siyag lain eSSS

**Comment by IrrationalCucumber** [comment]
> Pwede like inig human apply sa catcher, bisag pending pa ang application request kay di pa siya pwede makaapply lain errands. Nitry ko apply lain errands while pending pa application request. Ang mahitabo kay makaapply siyag lain errands.

Ma question ta ana, 
"what if ma deny iya application?"
"Nya mag huwat pa siya kanus a siya e accept?"
"what if ganahan ko multiple application for higher chance of landing a job?"

Mag add lang ko try og function mu check if no errand siya, if naa then dili ka accept ang employer

**Comment by markdannim** [comment]
> > Pwede like inig human apply sa catcher, bisag pending pa ang application request kay di pa siya pwede makaapply lain errands. Nitry ko apply lain errands while pending pa application request. Ang mahitabo kay makaapply siyag lain errands.
> 
> Ma question ta ana, "what if ma deny iya application?" "Nya mag huwat pa siya kanus a siya e accept?" "what if ganahan ko multiple application for higher chance of landing a job?"
> 
> Mag add lang ko try og function mu check if no errand siya, if naa then dili ka accept ang employer

image
di ko kapislit accept button tho si catcher way ongoing errands

**Pull request closed without merging**
